### ISSUE TITLE
ffmpeg.probe cannot read video information in FLV format

### ISSUE THREAD

**Issue by ggg-s** [ilucasgoncalves/VAVL#3]
(url)https://github.com/ilucasgoncalves/VAVL/blob/c128439ab6af171371f4581f68c21f2eabeb92a2/facial_features/utils/FaceVideoDataModule.py#LL461C11-L461C11)
<img width="157" alt="image" src="https://github.com/ilucasgoncalves/VAVL/assets/71912051/c2539c33-556e-47c0-8fdf-7ed641c140a1">

**Comment by ilucasgoncalves** [comment]
looks like some flv files from crema-d does not store all the metadata necessary for processing the videos. I have updated the code to handle this issue. It should work now. Let me know if you still have issues
